### ISSUE TITLE
Change shadow color of footer text

### ISSUE THREAD

**Issue by tequdev** [XRPLF/xrpl-dev-portal#2028]
The shadow of the text on the footer item is slightly different from the background color, which is somewhat uncomfortable.

The following and related files must be modified
- `styles/light/_light-theme.scss`
- `assets/css/devportal2022-v22.css`(maybe)

from
```css
.footer-nav{
  .nav-item{
    text-shadow: white 0px 0px 2px, white 1px 1px 2px, white 2px 2px 3px,
    white 2px 2px 4px, white 2px 2px 5px, white 2px 2px 6px, white -1px -1px 2px,
    white -2px -2px 3px, white -2px -2px 4px;
  }
}
```

to
```css
.footer-nav{
  .nav-item{
    text-shadow: #F5F5F7 0px 0px 2px, #F5F5F7 1px 1px 2px, #F5F5F7 2px 2px 3px,
    #F5F5F7 2px 2px 4px, #F5F5F7 2px 2px 5px, #F5F5F7 2px 2px 6px, #F5F5F7 -1px -1px 2px,
    #F5F5F7 -2px -2px 3px, #F5F5F7 -2px -2px 4px;
  }
}
```
--- 
Current
<img width="1523" alt="スクリーンショット 2023-07-28 22 12 59" src="https://github.com/XRPLF/xrpl-dev-portal/assets/69445828/d09dce85-c70d-459e-ace2-d6e171df2f3d">

After change
<img width="1546" alt="スクリーンショット 2023-07-28 22 23 07" src="https://github.com/XRPLF/xrpl-dev-portal/assets/69445828/115229bd-7615-49cf-ba05-c5feb0984875">
